import re

CHAT_CARD_TYPE = 'C'
TUTORIAL_CARD_TYPE = 'T'
INFORMATION_CARD_TYPE = 'I'

CHAT_CARD_RESOURCE_CODE_REGEX = re.compile(f'^{CHAT_CARD_TYPE}[0-9]+$')
TUTORIAL_CARD_RESOURCE_CODE_REGEX = re.compile(f'^{TUTORIAL_CARD_TYPE}[0-9]+$')
INFORMATION_CARD_RESOURCE_CODE_REGEX = re.compile(
    f'^{INFORMATION_CARD_TYPE}[0-9]+$')

CHAT_CARD_SENDER_TYPE = {
    'USER': 'USR',
    'BOT': 'BOT',
}

INFORMATION_CARD_RESOURCE_TYPE = {
    'URL': 'URL',
    'IMAGE': 'IMG',
    'TEXT': 'TXT',
}

TUTORIAL_CARD_FORWARD_CONDITION_TYPE = {
    'URL_MATCH': 'URL_MATCH',
}
